spring:
  config:
    name: ${spring.application.name}
  cloud.config:
    allowOverride: true
    overrideNone: false
    overrideSystemProperties: false
    name: ${spring.application.name}
  profiles.active: development

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

eureka:
  instance:
    preferIpAddress: false
    hostname: 192.168.170.54
  client:
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    healthcheck:
      enabled: true

feign.okhttp.enabled: true

---
spring:
  profiles: dev-eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://${MY_IP:localhost}:6761/eureka

---
spring:
  profiles: svt-eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka