spring:
  cloud.config:
    allowOverride: true
    overrideNone: false
    overrideSystemProperties: false
  profiles.active: development
management.contextPath: /manage #从新设置监控检查的地址，默认为/actuator
eureka:
  instance:
    statusPageUrlPath: ${management.contextPath}/info
    healthCheckUrlPath: ${management.contextPath}/status
    preferIpAddress: false
  client:
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    healthcheck:
      enabled: true

feign.okhttp.enabled: true
feign.hystrix.enabled: false #索性禁用Feign的Hystrix


---
spring:
  profiles: dev-eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://${MY_IP:localhost}:6761/eureka

---
spring:
  profiles: svt-eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureserver:6761/eureka