spring:
  cloud.config:
    allowOverride: true
    overrideNone: false
    overrideSystemProperties: false
  profiles.active: development
eureka.instance.preferIpAddress: true #以ip的方式注册到eurekaserver
feign.okhttp.enabled: true
feign.hystrix.enabled: false #索性禁用Feign的Hystrix


---
spring:
  profiles: dev-eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:6761/eureka

---
spring:
  profiles: svt-eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureserver:6761/eureka