spring:
  cloud.config:
    allowOverride: true
    overrideNone: false
    overrideSystemProperties: false
  profiles.active: development
---
spring:
  profiles: dev-eureka
eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://192.168.170.30:6761/eureka

---
spring:
  profiles: svt-eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureserver:6761/eureka