spring:
  cloud.config:
    allowOverride: true
    overrideNone: false
    overrideSystemProperties: false
  profiles.active: development
---
spring:
  profiles: dev-eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6761/eureka

---
spring:
  profiles: svt-eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureserver:6761/eureka