spring:
  config:
    name: ${spring.application.name}
  cloud.config:
    allowOverride: true
    overrideNone: false
    overrideSystemProperties: false
    name: ${spring.application.name}
  profiles.active: development

management:
  context-path: /manage #从新设置监控检查的地址，默认为/actuator
  security.enabled: false
  health:
    diskspace.enabled: false
  endpoint:
    health.enabled: true
  endpoints:
    web:
      path-mapping.health: status
      base-path: /manage #since spring boot 2.0.0 M6
      expose: info,status,health

eureka:
  instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/${management.endpoints.web.path-mapping.health}
    preferIpAddress: false
    hostname: localhost
  client:
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    healthcheck:
      enabled: true

feign.okhttp.enabled: true

---
spring:
  profiles: dev-eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://${MY_IP:localhost}:6761/eureka

---
spring:
  profiles: svt-eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureserver:6761/eureka