auth.name: zzlservice2
server.port: 7789
spring:
    profiles.include: dev-eureka
eureka.instance.preferIpAddress: true
eureka.instance.instance-id: 192.168.170.30:${spring.application.name}:${server.port}