auth.name: zzlservice1
server.port: 7788
spring:
  application:
    name: service1
    profiles.include: dev-eureka

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${server.port}